-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-4",
    mode = "2560x1440@120",
    position = "auto",
    scale = "auto",
    vrr = 1,
})

hl.monitor({
    output = "Unknown-1",
    disabled = true,
})

hl.monitor({
    output = "desc:Hisense Electric Co. Ltd. HISENSE 0x00000001",
    disabled = true,
})

hl.monitor({
    output = "desc:LG Electronics LG TV SSCR2 0x01010101",
    disabled = true,
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

-- exec-once = systemctl --user start xdg-desktop-portal-hyprland

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 3,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 2,
    bezier = "default",
})

hl.config({
    plugin = {
        hyprbars = {
            bar_height = 20,
            bar_color = "rgb(16161D)",
            ["col.text"] = "rgba(DCD7BAFF)",
            bar_part_of_window = true,
            bar_text_size = 10,
            bar_text_font = "Ubuntu Nerd Font",
            bar_button_padding = 10,
            bar_padding = 10,
            bar_precedence_over_border = true,
        },
    },
})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(DCD7BAFF)",
    size = 16,
    icon = "",
    action = "hyprctl dispatch killactive",
})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(DCD7BAFF)",
    size = 16,
    icon = "",
    action = "hyprctl dispatch fullscreen 2",
})

hl.plugin.hyprbars.add_button({
    bg_color = "rgba(00000000)",
    fg_color = "rgba(DCD7BAFF)",
    size = 16,
    icon = "",
    action = "hyprctl dispatch togglefloating",
})

hl.window_rule({
    name = "brighter-focused-bar",
    match = {
        focus = 1,
    },
    plugin = {
        hyprbars = {
            bar_color = "rgb(1F1F28)",
        },
    },
})

hl.window_rule({
    name = "hide-bar-on-non-floats",
    match = {
        float = 0,
    },
    plugin = {
        hyprbars = {
            no_bar = true,
        },
    },
})

hl.window_rule({
    match = {
        float = 1,
    },
    rounding = 8,
})

hl.window_rule({
    match = {
        class = "negative:(*.ghostty)",
    },
    no_dim = true,
})

hl.window_rule({
    match = {
        class = "(org.wezfurlong.*)",
    },
    workspace = "1",
})

hl.window_rule({
    match = {
        class = "(vesktop)",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        class = "(Zulip)",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        class = "(Tracy Profiler.*)",
    },
    workspace = "2",
    float = false,
})

hl.window_rule({
    match = {
        class = "(firefox)",
    },
    workspace = "3",
})

hl.window_rule({
    match = {
        class = "(brave)",
    },
    workspace = "3",
})

hl.window_rule({
    match = {
        class = "(thunderbird)",
    },
    workspace = "4",
})

hl.window_rule({
    match = {
        class = "(sublime_merge)",
    },
    workspace = "5",
})

hl.window_rule({
    match = {
        class = "(obsidian)",
    },
    workspace = "6",
})

hl.window_rule({
    match = {
        class = "(org.inkscape.Inkscape)",
    },
    workspace = "7",
})

hl.window_rule({
    match = {
        class = "(REAPER)",
    },
    workspace = "8",
})

hl.window_rule({
    match = {
        class = "(com.bitwig.*)",
    },
    workspace = "8",
})

hl.window_rule({
    match = {
        class = "(spicy)",
    },
    workspace = "9",
})

hl.window_rule({
    match = {
        class = "(org.keepassxc.KeePassXC)",
    },
    workspace = "10",
})

hl.window_rule({
    match = {
        class = "^(libreoffice.*)$",
    },
    suppress_event = "fullscreen",
})

hl.window_rule({
    match = {
        class = "(^soffice)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(pinentry-)",
    },
    stay_focused = true,
})

hl.window_rule({
    match = {
        title = "(.*REAPER v\\d.\\d.*)",
    },
    float = false,
})

hl.window_rule({
    match = {
        float = 0,
    },
    no_shadow = true,
})

hl.window_rule({
    match = {
        class = "(zenity)",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        class = "(xdg-desktop-portal-gtk)",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open File)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Select a File)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Choose wallpaper)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Open Folder)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Save As)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(Library)(.*)$",
    },
    center = true,
    float = true,
})

hl.window_rule({
    match = {
        title = "^(File Upload)(.*)$",
    },
    center = true,
    float = true,
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + return", hl.dsp.exec_cmd("uwsm app -- ghostty"))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("uwsm app -- fuzzel --launch-prefix 'uwsm app -- ' --list-executables-in-path --terminal 'ghostty -e'"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("uwsm app -- pick-firefox-bookmark"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("uwsm app -- bemoji --type"))
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("uwsm app -- search-web"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("uwsm app -- pick-symbol"))

hl.bind("Pause", hl.dsp.exec_cmd("transcribe"))
hl.bind("Pause", hl.dsp.exec_cmd("sleep 0.2 && transcribe | wtype -"), { release = true })

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind("SUPER + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("SUPER + Tab", hl.dsp.window.bring_to_top())

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("uwsm app -- wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("uwsm app -- wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true })

hl.bind("PRINT", hl.dsp.exec_cmd("uwsm app -- take-screenshot"))
hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd("uwsm app -- record-screen"))

hl.config({
    input = {
        -- 0 - Cursor movement will not change focus.
        -- 1 - Cursor movement will always change focus to the window under the cursor.
        -- 2 - Cursor focus will be detached from keyboard focus. Clicking on a window will move keyboard focus to that window.
        -- 3 - Cursor focus will be completely separate from keyboard focus. Clicking on a window will not change keyboard focus.
        follow_mouse = 2,
        repeat_rate = 35, -- repeats per second
        repeat_delay = 300, -- milliseconds before repeating
    },
    general = {
        gaps_in = 0, -- gaps between windows
        gaps_out = 0, -- gaps between windows and screen edges
        border_size = 0,
        col = {
            active_border = "rgba(00000080)",
            inactive_border = "rgba(00000080)",
        },
        resize_on_border = true,
        layout = "master",
    },
    decoration = {
        rounding = 0,
        dim_inactive = true,
        dim_strength = 0.2,
        shadow = {
            enabled = true,
            ignore_window = true,
            range = 60,
            offset = "2 4",
            render_power = 4,
            color = "rgba(0000002A)",
        },
    },
    animations = {
        enabled = true,
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = 0x090909,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd(string.format("hyprctl setcursor %s %d", CURSOR_NAME, CURSOR_SIZE))
    hl.exec_cmd("uwsm app -- waybar")
    hl.exec_cmd("uwsm app -- vesktop")
    hl.exec_cmd("uwsm app -- keepassxc")
    hl.exec_cmd("uwsm app -- sublime_merge")
    hl.exec_cmd("systemctl --user enable --now hypridle.service")
    hl.exec_cmd("systemctl --user enable --now hyprpaper.service")
end)
