#!/usr/bin/env python3

from pathlib import Path
from wezterm_setup_core import Project, WeztermSetupBuilder
import sys

if __name__ == "__main__":
    project = Project(project_dir=Path.home() / "Projects" / "floe")
    builder = WeztermSetupBuilder(project)

    editor_tab = builder.add_tab(command="nix develop .#with-validators", title="Editor")
    builder.send_text(editor_tab, "nvim\n")

    docs_tab = builder.add_tab(command="nix develop .#with-validators", title="Website")
    builder.send_text(docs_tab, "zig build script:website-dev")

    shell_tab = builder.add_tab(command="nix develop .#with-validators", title="Shell")
    builder.send_text(shell_tab, "git pull\nbash .workshop/build.sh\n")

    # shell_tab = builder.add_tab(title="Log")
    #
    # log_folder = "" 
    # if sys.platform == "darwin":
    #     log_folder = "~/Library/Logs/Floe"
    # elif sys.platform == "linux":
    #     log_folder = "~/.local/state/Floe/Logs"
    # builder.send_text(shell_tab, f"cd {log_folder}\nnvim\n 1:terminal tail -f -n 10000 latest.log\nG")

    builder.activate_tab(editor_tab)
