#!/usr/bin/env python3

from pathlib import Path
from wezterm_setup_core import Project, WeztermSetupBuilder

if __name__ == "__main__":
    project = Project(project_dir=Path.home() / "Projects" / "floe")
    builder = WeztermSetupBuilder(project)

    editor_tab = builder.add_tab(command="nix develop", title="Editor")
    builder.send_text(editor_tab, "nvim\n")

    docs_tab = builder.add_tab(command="nix develop", title="Docs Server")
    builder.send_text(docs_tab, "cd docs\nmdbook serve\n")

    shell_tab = builder.add_tab(command="nix develop", title="Shell")
    builder.send_text(shell_tab, "git pull\njust default\n")

    builder.activate_tab(editor_tab)
