#!/usr/bin/env python3

from pathlib import Path
from wezterm_setup_core import Project, WeztermSetupBuilder
import os

if __name__ == "__main__":
    project = Project(project_dir=Path.home() / "Projects" / "frozenplain.com")
    builder = WeztermSetupBuilder(project)

    pane0 = builder.ensure_wezterm_running()
    builder.set_pane_title(pane0, "Editor")
    builder.send_text(pane0, "nvim\n")

    pane1 = builder.spawn_pane(pane0, command="npm run dev")
    builder.set_pane_title(pane1, "Dev Server")

    pane2 = builder.spawn_pane(pane0)
    builder.set_pane_title(pane2, "Shell")

    builder.activate_pane(pane0)

    builder.run_command(["firefox", "--new-tab", "http://localhost:5173/"])
    builder.switch_hyprland_workspace("1")
