#!/usr/bin/env python3

from pathlib import Path
from wezterm_setup_core import Project, WeztermSetupBuilder
import os

if __name__ == "__main__":
    project = Project(project_dir=Path.home() / "Projects" / "frozenplain.com")
    builder = WeztermSetupBuilder(project)

    editor_tab = builder.add_tab()
    builder.send_text(editor_tab, "nvim\n")

    builder.add_tab(command="npm run dev -- --open", title="Dev Server")

    shell_tab = builder.add_tab(title="Shell")
    builder.send_text(shell_tab, "git pull\n")

    builder.activate_tab(editor_tab)

    builder.switch_hyprland_workspace("1")
