#!/usr/bin/env bash
# New Window Neovim. Use provided path or current directory path
local target="$(readlink -f "${1:-$(pwd)}")"  # Convert to absolute path
wezterm cli spawn --new-window -- nvim "$target"
