#!/usr/bin/env python3

from pathlib import Path
from wezterm_setup_core import Project, WeztermSetupBuilder

if __name__ == "__main__":
    project = Project(project_dir=Path.home() / ".config" / "home-manager")
    builder = WeztermSetupBuilder(project)

    editor_tab = builder.add_tab(title="Editor")
    builder.send_text(editor_tab, "nvim\n")

    shell_tab = builder.add_tab(title="Shell")
    builder.send_text(shell_tab, "git pull\n")

    builder.activate_tab(editor_tab)

