#!/usr/bin/env python3

from pathlib import Path
from wezterm_setup_core import Project, WeztermSetupBuilder

if __name__ == "__main__":
    project = Project(project_dir=Path.home() / ".config" / "home-manager")
    builder = WeztermSetupBuilder(project)

    pane0 = builder.ensure_wezterm_running()
    builder.set_pane_title(pane0, "Editor")
    builder.send_text(pane0, "nvim\n")

    pane1 = builder.spawn_pane(pane0)
    builder.set_pane_title(pane1, "Shell")

    builder.activate_pane(pane0)

