# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxKernel.packages.linux_6_12;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f54c0778-3ca3-42f5-a75d-1e70eec5a18d";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C269-CECF";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/nix/store" = {
    device = "/dev/disk/by-uuid/81e9bc10-f452-4981-a294-e6bf2e71c98b";
    fsType = "btrfs";
    neededForBoot = true;
    options = [
      "subvol=@nix-store"
      "compress=zstd:1"
      "noatime"
    ];
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/81e9bc10-f452-4981-a294-e6bf2e71c98b";
    fsType = "btrfs";
    options = [
      "subvol=@data"
      "noatime"
    ];
  };

  # fileSystems."/mnt/FrozenVault" = {
  #   device = "systemd-1";
  #   fsType = "autofs";
  # };

  fileSystems."/mnt/SSHD" = {
    device = "/dev/disk/by-label/SSHD";
    fsType = "ntfs";
    options = [
      "defaults"
      "user"
      "rw"
      "uid=1000"
      "nofail"
    ];
  };

  fileSystems."/mnt/GamesSSD" = {
    device = "/dev/disk/by-label/Games\\x20SSD";
    fsType = "ntfs";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
      "umask=0022"
      "exec"
      "windows_names"
    ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp11s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp12s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
